extends:
  - airbnb
plugins:
  - import
  - react
env:
  browser: true
  node: true
rules:
  import/no-unresolved: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-extend-native: off
  max-len: off